### ISSUE TITLE
Dockerhub official image

### ISSUE THREAD

**Issue by KotskinKotskin** [Bearer/Pizzly#174]
Hi, great product! 

Can you please provide offical image of pizzly to dockerhub?  Or, clear instruction to docker-based installation. Thank you.

**Comment by rienafairefr** [comment]
I second this. As is, the repo's Dockerfile is not buildable (there is a undocumented `config` file/directory needed)

**Comment by Frenchcooc** [comment]
Thanks for the request! I'm not really familiar with Docker. If anyone experimented is interested to share good resources or a MVP, that would be really great!

**Comment by KotskinKotskin** [comment]
@Frenchcooc can you please specify ENV variables for config? I will try create image

**Comment by Frenchcooc** [comment]
Sure! All ENV variables used by Pizzly are exposed here: https://github.com/Bearer/Pizzly/blob/master/.envrc.example

**Comment by Nightbr** [comment]
Hey, here is how I Dockerized Pizzly:

1- Add a startup.sh at root (I will use this script to execute startup script such as migration and start the App)
```bash
#!/bin/sh

# Docker Startup script

# Apply migration
./node_modules/.bin/knex --cwd ./src/lib/database/config migrate:latest

# Start App
node ./src/index.js

```

2- Here is the updated Dockerfile

```Dockerfile
# This is the Dockerfile for building a production image with Pizzly

# Build image
FROM node:14-slim

WORKDIR /app

# Copy in dependencies for building
COPY *.json ./
COPY yarn.lock ./
# COPY config ./config
COPY integrations ./integrations/
COPY src ./src/
COPY tests ./tests/
COPY views ./views/

RUN yarn install


# Actual image to run from.
FROM node:14-slim

# Make sure we have ca certs for TLS
RUN apt-get update && apt-get install -y \
  curl \
  wget \
  gnupg2 ca-certificates libnss3  \
  git

# Make a directory for the node user. Not running Pizzly as root.
RUN mkdir /home/node/app && chown -R node:node /home/node/app
WORKDIR /home/node/app

USER node

# Startup script
COPY --chown=node:node ./startup.sh ./startup.sh
RUN chmod +x ./startup.sh
# COPY from first container
COPY --chown=node:node --from=0 /app/package.json ./package.json
COPY --chown=node:node --from=0 /app/dist/ .
COPY --chown=node:node --from=0 /app/views ./views
COPY --chown=node:node --from=0 /app/node_modules ./node_modules

# Run the startup script
CMD ./startup.sh

EXPOSE 8080
```

3- This is my docker-compose.yml to use the Docker image but you can build it and push it to your Docker registry (Docker Hub, ECR, Gitlab Registry, ...)

```
version: '3.6'

networks:
  database:
    driver: ${NETWORKS_DRIVER}

volumes:
  postgres:
    driver: ${VOLUMES_DRIVER}

services:
  ### Pizzly - OAuth service ####################################
  oauth:
    build:
      context: ./pizzly
    ports:
      - 8080:8080
    networks:
      - database
      - default
    environment:
      NODE_ENV: production
      DASHBOARD_USERNAME: admin
      DASHBOARD_PASSWORD: admin
      SECRET_KEY: devSecretKey
      PUBLISHABLE_KEY: devPubKey
      PROXY_USES_SECRET_KEY_ONLY: "FALSE"
      COOKIE_SECRET: devCookieSecret
      AUTH_CALLBACK_URL: https://localhost/auth/callback
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: oauth_db
      DB_USER: root
      DB_PASSWORD: root


  ### Postgres Database #########################################
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    networks:
      - database
    volumes:
    - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: oauth_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

```

You run `docker-compose up -d` and you could access the UI through http://localhost:8080
